---
title: "Lines, Curves, Tangents, Distance, Length, and Area"
author: "W. Bauer"
date: "01/10/2015"
output: html_document
---

1. Plane geometry is about lines and curves.
```{r echo=FALSE, fig.show='hold'}
plot(c(0,10), c(0,10), type='n', xlab="x", ylab="y", main="Lines and curves")
abline(h=0:10, col="lightblue", lwd=2)
abline(v=0:10, col="lightblue", lwd=2)
segments(1,6,5,9, lwd=3)
points(c(1,5),c(6,9), pch=19, cex=1.5)
points(8,6,cex=25,lwd=3)
x <- seq(-1, 11, by=.5)
lines(x, 1+sin(.2*pi*x), lwd=3)
```

2. Lines have length and slopes.
```{r echo=FALSE, fig.show='hold'}
plot(c(0,10), c(0,10), type='n', xlab="x", ylab="y", main="Line segments have slopes and lengths.")
abline(h=0:10, col="lightblue", lwd=2)
abline(v=0:10, col="lightblue", lwd=2)
segments(1,6,5,9, lwd=3)
points(c(1,5),c(6,9), pch=19, cex=1.5)
segments(1,6,5,6, lty=2, lwd=3, col=2)
segments(5,6,5,9, lty=2, lwd=3, col=2)
text(3.25, 5.5, expression(4), lwd=3, cex=1.5, col=2)
text(5.25, 7.5, expression(3), lwd=3, cex=1.5, col=2)
text(2.5, 8.5, expression(sqrt(4^2 + 3^2)), lwd=3, cex=1.5, col=1)
text(1.3, 8.5, "length = ", lwd=3, cex=1.5, col=1)
text(5.75, 5, expression(frac(3,4)), lwd=3, cex=1.5, col=2)
text(5, 5, "slope = ", lwd=3, cex=1.5, col=2)
```

3. The closer you look at a smooth curve, the more it looks like a line.